export const LOAD_PRODUCTS_INIT='LOAD_PRODUCTS_INIT'
export const LOAD_PRODUCTS_SUCCESS='LOAD_PRODUCTS_SUCCESS'
export const LOAD_PRODUCTS_FAIL='LOAD_PRODUCTS_FAIL'
export const ADD_PRODUCT_CUSTOMIZE='ADD_PRODUCT_CUSTOMIZE'

export const INSERT_PRODUCT_INIT='INSERT_PRODUCT_INIT'
export const INSERT_PRODUCT='INSERT_PRODUCT'
export const INSERT_PRODUCT_FAIL='INSERT_PRODUCT_FAIL'

export const ORDERED_LOAD_PRODUCTS_SUCCESS='ORDERED_LOAD_PRODUCTS_SUCCESS'

export const MODAL_BACK_HANDLER='MODAL_BACK_HANDLER'